products:
  badfuncs:
    build:
      output-dir: ./badfuncs/build
      main-pkg: ./badfuncs/
      environment:
        CGO_ENABLED: "0"
    dist:
      output-dir: ./badfuncs/dist
      dist-type:
        type: bin
        info:
          omit-init-sh: true
