products:
  nobadfuncs:
    build:
      output-dir: ./nobadfuncs/build
      main-pkg: ./nobadfuncs/
      environment:
        CGO_ENABLED: "0"
    dist:
      output-dir: ./nobadfuncs/dist
      dist-type:
        type: bin
        info:
          omit-init-sh: true
